// Code generated by the Encore 1.50.0 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly appointments: appointments.ServiceClient
    public readonly auth: auth.ServiceClient
    public readonly contacts: contacts.ServiceClient
    public readonly customers: customers.ServiceClient
    public readonly employees: employees.ServiceClient
    public readonly masterdata: masterdata.ServiceClient
    public readonly orders: orders.ServiceClient
    public readonly payments: payments.ServiceClient
    public readonly reports: reports.ServiceClient
    public readonly users: users.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.appointments = new appointments.ServiceClient(base)
        this.auth = new auth.ServiceClient(base)
        this.contacts = new contacts.ServiceClient(base)
        this.customers = new customers.ServiceClient(base)
        this.employees = new employees.ServiceClient(base)
        this.masterdata = new masterdata.ServiceClient(base)
        this.orders = new orders.ServiceClient(base)
        this.payments = new payments.ServiceClient(base)
        this.reports = new reports.ServiceClient(base)
        this.users = new users.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * Import the auth handler to be able to derive the auth type
 */
import type { auth as auth_auth } from "~backend/auth/auth";

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: RequestType<typeof auth_auth> | AuthDataGenerator
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_appointments_create_create } from "~backend/appointments/create";
import { getByCustomer as api_appointments_get_by_customer_getByCustomer } from "~backend/appointments/get_by_customer";
import { list as api_appointments_list_list } from "~backend/appointments/list";
import { update as api_appointments_update_update } from "~backend/appointments/update";

export namespace appointments {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.getByCustomer = this.getByCustomer.bind(this)
            this.list = this.list.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new appointment
         */
        public async create(params: RequestType<typeof api_appointments_create_create>): Promise<ResponseType<typeof api_appointments_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/appointments`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_appointments_create_create>
        }

        /**
         * Get all appointments for a specific customer
         */
        public async getByCustomer(params: RequestType<typeof api_appointments_get_by_customer_getByCustomer>): Promise<ResponseType<typeof api_appointments_get_by_customer_getByCustomer>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                fromDate: params.fromDate === undefined ? undefined : params.fromDate.toISOString(),
                status:   params.status,
                toDate:   params.toDate === undefined ? undefined : params.toDate.toISOString(),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/appointments/customer/${encodeURIComponent(params.customerId)}`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_appointments_get_by_customer_getByCustomer>
        }

        /**
         * Lists appointments with filtering
         */
        public async list(params: RequestType<typeof api_appointments_list_list>): Promise<ResponseType<typeof api_appointments_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                assignedToId:   params.assignedToId,
                customerId:     params.customerId,
                customerSearch: params.customerSearch,
                fromDate:       params.fromDate === undefined ? undefined : params.fromDate.toISOString(),
                limit:          params.limit === undefined ? undefined : String(params.limit),
                page:           params.page === undefined ? undefined : String(params.page),
                status:         params.status,
                toDate:         params.toDate === undefined ? undefined : params.toDate.toISOString(),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/appointments`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_appointments_list_list>
        }

        public async update(params: RequestType<typeof api_appointments_update_update>): Promise<ResponseType<typeof api_appointments_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                description:     params.description,
                duration:        params.duration,
                reminderMinutes: params.reminderMinutes,
                scheduledAt:     params.scheduledAt,
                status:          params.status,
                title:           params.title,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/appointments/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_appointments_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { initializeSystem as api_auth_initialize_initializeSystem } from "~backend/auth/initialize";
import { login as api_auth_login_login } from "~backend/auth/login";
import {
    changePassword as api_auth_password_changePassword,
    resetPassword as api_auth_password_resetPassword
} from "~backend/auth/password";
import { setupDefaultUsers as api_auth_setup_default_setupDefaultUsers } from "~backend/auth/setup-default";

export namespace auth {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.changePassword = this.changePassword.bind(this)
            this.initializeSystem = this.initializeSystem.bind(this)
            this.login = this.login.bind(this)
            this.resetPassword = this.resetPassword.bind(this)
            this.setupDefaultUsers = this.setupDefaultUsers.bind(this)
        }

        /**
         * Admin can change any employee's password
         */
        public async changePassword(params: RequestType<typeof api_auth_password_changePassword>): Promise<ResponseType<typeof api_auth_password_changePassword>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/change-password`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_password_changePassword>
        }

        /**
         * Initialize system with properly hashed passwords (admin only, one-time setup)
         */
        public async initializeSystem(params: RequestType<typeof api_auth_initialize_initializeSystem>): Promise<ResponseType<typeof api_auth_initialize_initializeSystem>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/initialize`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_initialize_initializeSystem>
        }

        /**
         * Simple login for demo - in production use proper authentication with hashed passwords
         */
        public async login(params: RequestType<typeof api_auth_login_login>): Promise<ResponseType<typeof api_auth_login_login>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/login`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_login_login>
        }

        /**
         * Admin can reset employee password to default
         */
        public async resetPassword(params: RequestType<typeof api_auth_password_resetPassword>): Promise<ResponseType<typeof api_auth_password_resetPassword>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/reset-password`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_password_resetPassword>
        }

        /**
         * Tạo hash mật khẩu cho tài khoản mặc định
         */
        public async setupDefaultUsers(params: RequestType<typeof api_auth_setup_default_setupDefaultUsers>): Promise<ResponseType<typeof api_auth_setup_default_setupDefaultUsers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/setup-default`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_setup_default_setupDefaultUsers>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_contacts_create_create } from "~backend/contacts/create";
import { list as api_contacts_list_list } from "~backend/contacts/list";

export namespace contacts {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.list = this.list.bind(this)
        }

        /**
         * Creates a new contact history entry
         */
        public async create(params: RequestType<typeof api_contacts_create_create>): Promise<ResponseType<typeof api_contacts_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/contacts`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_contacts_create_create>
        }

        /**
         * Lists contact history for a customer
         */
        public async list(params: RequestType<typeof api_contacts_list_list>): Promise<ResponseType<typeof api_contacts_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: params.limit === undefined ? undefined : String(params.limit),
                page:  params.page === undefined ? undefined : String(params.page),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/contacts/${encodeURIComponent(params.customerId)}`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_contacts_list_list>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_customers_create_create } from "~backend/customers/create";
import { deleteCustomer as api_customers_delete_deleteCustomer } from "~backend/customers/delete";
import { exportCustomers as api_customers_export_exportCustomers } from "~backend/customers/export";
import { get as api_customers_get_get } from "~backend/customers/get";
import { list as api_customers_list_list } from "~backend/customers/list";
import { update as api_customers_update_update } from "~backend/customers/update";

export namespace customers {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.deleteCustomer = this.deleteCustomer.bind(this)
            this.exportCustomers = this.exportCustomers.bind(this)
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new customer
         */
        public async create(params: RequestType<typeof api_customers_create_create>): Promise<ResponseType<typeof api_customers_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/customers`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_customers_create_create>
        }

        /**
         * Deletes a customer (admin only) - soft delete
         */
        public async deleteCustomer(params: { id: string }): Promise<ResponseType<typeof api_customers_delete_deleteCustomer>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/customers/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_customers_delete_deleteCustomer>
        }

        /**
         * Export customers to Excel
         */
        public async exportCustomers(params: RequestType<typeof api_customers_export_exportCustomers>): Promise<ResponseType<typeof api_customers_export_exportCustomers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/customers/export`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_customers_export_exportCustomers>
        }

        /**
         * Gets a single customer by ID
         */
        public async get(params: { id: string }): Promise<ResponseType<typeof api_customers_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/customers/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_customers_get_get>
        }

        /**
         * Lists customers with filtering, sorting, and pagination
         */
        public async list(params: RequestType<typeof api_customers_list_list>): Promise<ResponseType<typeof api_customers_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                assignedSalespersonId: params.assignedSalespersonId,
                contactStatusId:       params.contactStatusId,
                createdFrom:           params.createdFrom === undefined ? undefined : params.createdFrom.toISOString(),
                createdTo:             params.createdTo === undefined ? undefined : params.createdTo.toISOString(),
                limit:                 params.limit === undefined ? undefined : String(params.limit),
                page:                  params.page === undefined ? undefined : String(params.page),
                productId:             params.productId,
                provinceId:            params.provinceId,
                search:                params.search,
                sortBy:                params.sortBy,
                sortOrder:             params.sortOrder,
                stageId:               params.stageId,
                temperatureId:         params.temperatureId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/customers`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_customers_list_list>
        }

        /**
         * Updates an existing customer
         */
        public async update(params: RequestType<typeof api_customers_update_update>): Promise<ResponseType<typeof api_customers_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                address:               params.address,
                assignedSalespersonId: params.assignedSalespersonId,
                businessTypeId:        params.businessTypeId,
                companyName:           params.companyName,
                companySizeId:         params.companySizeId,
                contactStatusId:       params.contactStatusId,
                customerFeedback:      params.customerFeedback,
                customerTypeId:        params.customerTypeId,
                email:                 params.email,
                leadSourceId:          params.leadSourceId,
                name:                  params.name,
                notes:                 params.notes,
                phone:                 params.phone,
                productIds:            params.productIds,
                provinceId:            params.provinceId,
                stageId:               params.stageId,
                temperatureId:         params.temperatureId,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/customers/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_customers_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_employees_create_create } from "~backend/employees/create";
import { deleteEmployee as api_employees_delete_deleteEmployee } from "~backend/employees/delete";
import { list as api_employees_list_list } from "~backend/employees/list";
import { update as api_employees_update_update } from "~backend/employees/update";

export namespace employees {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.deleteEmployee = this.deleteEmployee.bind(this)
            this.list = this.list.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new employee (admin only)
         */
        public async create(params: RequestType<typeof api_employees_create_create>): Promise<ResponseType<typeof api_employees_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/employees`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_employees_create_create>
        }

        /**
         * Deletes an employee (admin only) - soft delete by setting active = false
         */
        public async deleteEmployee(params: { id: string }): Promise<ResponseType<typeof api_employees_delete_deleteEmployee>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/employees/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_employees_delete_deleteEmployee>
        }

        /**
         * Lists all employees (admin only)
         */
        public async list(): Promise<ResponseType<typeof api_employees_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/employees`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_employees_list_list>
        }

        /**
         * Updates an employee (admin only)
         */
        public async update(params: RequestType<typeof api_employees_update_update>): Promise<ResponseType<typeof api_employees_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                active: params.active,
                email:  params.email,
                name:   params.name,
                phone:  params.phone,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/employees/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_employees_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createItem as api_masterdata_create_item_createItem } from "~backend/masterdata/create_item";
import { deleteItem as api_masterdata_delete_item_deleteItem } from "~backend/masterdata/delete_item";
import { getAll as api_masterdata_get_all_getAll } from "~backend/masterdata/get_all";
import { listItems as api_masterdata_list_items_listItems } from "~backend/masterdata/list_items";
import { updateItem as api_masterdata_update_item_updateItem } from "~backend/masterdata/update_item";

export namespace masterdata {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createItem = this.createItem.bind(this)
            this.deleteItem = this.deleteItem.bind(this)
            this.getAll = this.getAll.bind(this)
            this.listItems = this.listItems.bind(this)
            this.updateItem = this.updateItem.bind(this)
        }

        /**
         * Creates a new master data item
         */
        public async createItem(params: RequestType<typeof api_masterdata_create_item_createItem>): Promise<ResponseType<typeof api_masterdata_create_item_createItem>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                name: params.name,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/masterdata/${encodeURIComponent(params.table)}`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_masterdata_create_item_createItem>
        }

        /**
         * Deletes a master data item (hard delete)
         */
        public async deleteItem(params: { table: string, id: string }): Promise<ResponseType<typeof api_masterdata_delete_item_deleteItem>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/masterdata/${encodeURIComponent(params.table)}/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_masterdata_delete_item_deleteItem>
        }

        /**
         * Gets all master data for form dropdowns
         */
        public async getAll(): Promise<ResponseType<typeof api_masterdata_get_all_getAll>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/masterdata`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_masterdata_get_all_getAll>
        }

        /**
         * Gets master data items for a specific table
         */
        public async listItems(params: { table: string }): Promise<ResponseType<typeof api_masterdata_list_items_listItems>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/masterdata/${encodeURIComponent(params.table)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_masterdata_list_items_listItems>
        }

        /**
         * Updates a master data item
         */
        public async updateItem(params: RequestType<typeof api_masterdata_update_item_updateItem>): Promise<ResponseType<typeof api_masterdata_update_item_updateItem>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                active: params.active,
                name:   params.name,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/masterdata/${encodeURIComponent(params.table)}/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_masterdata_update_item_updateItem>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_orders_create_create } from "~backend/orders/create";
import { list as api_orders_list_list } from "~backend/orders/list";

export namespace orders {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.list = this.list.bind(this)
        }

        public async create(params: RequestType<typeof api_orders_create_create>): Promise<ResponseType<typeof api_orders_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/orders`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_orders_create_create>
        }

        public async list(params: RequestType<typeof api_orders_list_list>): Promise<ResponseType<typeof api_orders_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                customerId: params.customerId,
                dateFrom:   params.dateFrom === undefined ? undefined : params.dateFrom.toISOString(),
                dateTo:     params.dateTo === undefined ? undefined : params.dateTo.toISOString(),
                limit:      params.limit === undefined ? undefined : String(params.limit),
                page:       params.page === undefined ? undefined : String(params.page),
                status:     params.status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/orders`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_orders_list_list>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_payments_create_create } from "~backend/payments/create";
import { list as api_payments_list_list } from "~backend/payments/list";

export namespace payments {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.list = this.list.bind(this)
        }

        public async create(params: RequestType<typeof api_payments_create_create>): Promise<ResponseType<typeof api_payments_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/payments`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_payments_create_create>
        }

        public async list(params: RequestType<typeof api_payments_list_list>): Promise<ResponseType<typeof api_payments_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                customerId: params.customerId,
                dateFrom:   params.dateFrom === undefined ? undefined : params.dateFrom.toISOString(),
                dateTo:     params.dateTo === undefined ? undefined : params.dateTo.toISOString(),
                limit:      params.limit === undefined ? undefined : String(params.limit),
                orderId:    params.orderId,
                page:       params.page === undefined ? undefined : String(params.page),
                status:     params.status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/payments`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_payments_list_list>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getDashboard as api_reports_dashboard_getDashboard } from "~backend/reports/dashboard";

export namespace reports {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getDashboard = this.getDashboard.bind(this)
        }

        /**
         * Gets dashboard statistics
         */
        public async getDashboard(): Promise<ResponseType<typeof api_reports_dashboard_getDashboard>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/reports/dashboard`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_reports_dashboard_getDashboard>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { list as api_users_list_list } from "~backend/users/list";

export namespace users {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.list = this.list.bind(this)
        }

        /**
         * Lists all users (admin only)
         */
        public async list(): Promise<ResponseType<typeof api_users_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_users_list_list>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | RequestType<typeof auth_auth>
  | Promise<RequestType<typeof auth_auth> | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.50.0)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: RequestType<typeof auth_auth> | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
